### ISSUE TITLE
Chapter 9, before chasing, no wait

### ISSUE THREAD

**Issue by entonos** [PacktPublishing/Blueprints-Visual-Scripting-for-Unreal-Engine-Second-Edition#1]
Before adding the Pawn Sensing, the Enemy does not pause when it reaches a Target point. This is because the CurrentPoint is updated once the Enemy reaches the Target and so Wait node is never executed. I added a Delay at the end of the chain in EnemyCharacter that updates the next patrol point and fed in a Random Float in Range to the Delay whose input execution pin is connected to the two Set Current Patrol Point output execution pins. I then connected the Delay execution output pin to the Set Value as Object. The two Set Current Patrol Point were not connected to the Set Value as Object in the book  but is included in the the git repository.

**Comment by MarcosRomero** [comment]
Hi. Thank you very much for your contribution. There are several ways to adjust the wait behavior. I don't want to modify the source code because it will be confusing for the reader if the code is different from what is described in the book. In relation to the two Set Current Patrol Point connections, I mention them in the first paragraph of page 183.

**Comment by entonos** [comment]
Yes, you are correct, you did mention to connect the pins from the two Set Current Patrol Point to Set Value as Object. In the picture previous to that paragraph it might have been useful to show the output execution pins going somewhere (it would have clued me in, at least). Agree you should not adjust the source code to avoid confusion. Thank you for writing the book- I did find it straight forward and useful.
